#ifndef CONFIGIT2704_H
#define CONFIGIT2704_H

#include "../../config.h"

#define IT2704_COMMON                                           0x3001U
#define COMMON_RESET                                            SUBIDX_1
#define COMMON_POWER_ON_MODE                                    SUBIDX_2
#define COMMON_SOURCE_SLOPE_TYPE                                SUBIDX_3
#define COMMON_LOAD_CURRENT_SYMBOL                              SUBIDX_4
#define COMMON_OUTPUT_COUPLE                                    SUBIDX_5
#define COMMON_OUTPUT_COUPLE_MODE                               SUBIDX_6
#define COMMON_OUTPUT_COUPLE_OFFSET                             SUBIDX_7
#define COMMON_INHIBIT_COUPLE                                   SUBIDX_8
#define COMMON_INHIBIT_COUPLE_MOE                               SUBIDX_9
#define COMMON_PROTECTION_COUPLE                                SUBIDX_10

#define IT2704_SOURCE_CURRENT                                   0x3002U
#define IT2704_SOURCE_CURRENT_CURRENT_LEVEL                     SUBIDX_1
#define IT2704_SOURCE_CURRENT_CURRENT_TRIGGRED                  SUBIDX_2
#define IT2704_SOURCE_CURRENT_CURRENT_LIMIT_POSITIVE            SUBIDX_3
#define IT2704_SOURCE_CURRENT_CURRENT_LIMIT_NEGATIVE            SUBIDX_4
#define IT2704_SOURCE_CURRENT_CURRENT_LIMIT_COUPLE              SUBIDX_5
#define IT2704_SOURCE_CURRENT_CURRENT_MODE                      SUBIDX_6
#define IT2704_SOURCE_CURRENT_CURRENT_RANGE                     SUBIDX_7
#define IT2704_SOURCE_CURRENT_CURRENT_SLEW_POSITIVE             SUBIDX_8
#define IT2704_SOURCE_CURRENT_CURRENT_SLEW_NEGATIVE             SUBIDX_9
#define IT2704_SOURCE_CURRENT_CURRENT_SLEW_TIME_POSITIVE        SUBIDX_10
#define IT2704_SOURCE_CURRENT_CURRENT_SLEW_TIME_NEGATIVE        SUBIDX_11
#define IT2704_SOURCE_CURRENT_CURRENT_SLEW_COUPLE               SUBIDX_12
#define IT2704_SOURCE_CURRENT_CURRENT_SLEW_POSITIVE_MAX         SUBIDX_13
#define IT2704_SOURCE_CURRENT_CURRENT_SLEW_NEGATIVE_MAX         SUBIDX_14
#define IT2704_SOURCE_CURRENT_SINK_RES_STATE                    SUBIDX_15
#define IT2704_SOURCE_CURRENT_SINK_RES_LEVEL                    SUBIDX_16
#define IT2704_SOURCE_CURRENT_OVER_CURRENT_PROTECT_STATE        SUBIDX_17
#define IT2704_SOURCE_CURRENT_OVER_CURRENT_PROTECT_POSITIVE     SUBIDX_18
#define IT2704_SOURCE_CURRENT_OVER_CURRENT_PROTECT_NEGATIVE     SUBIDX_19
#define IT2704_SOURCE_CURRENT_OVER_CURRENT_PROTECT_DELAY        SUBIDX_20
#define IT2704_SOURCE_CURRENT_UNDER_CURRENT_PROTECT_STATE       SUBIDX_21
#define IT2704_SOURCE_CURRENT_UNDER_CURRENT_PROTECT_POSITIVE    SUBIDX_22
#define IT2704_SOURCE_CURRENT_UNDER_CURRENT_PROTECT_NEGATIVE    SUBIDX_23
#define IT2704_SOURCE_CURRENT_UNDER_CURRENT_PROTECT_DELAY       SUBIDX_24
#define IT2704_SOURCE_CURRENT_UNDER_CURRENT_PROTECT_WARM        SUBIDX_25

#define IT2704_SOURCE_VOLTAGE                                   0x3003U
#define IT2704_SOURCE_VOLTAGE_VOLTAGE_LEVEL                     SUBIDX_1
#define IT2704_SOURCE_VOLTAGE_VOLTAGE_TRIGGRED                  SUBIDX_2
#define IT2704_SOURCE_VOLTAGE_VOLTAGE_LIMIT_POSITIVE            SUBIDX_3
#define IT2704_SOURCE_VOLTAGE_VOLTAGE_LIMIT_NEGATIVE            SUBIDX_4
#define IT2704_SOURCE_VOLTAGE_VOLTAGE_LIMIT_COUPLE              SUBIDX_5
#define IT2704_SOURCE_VOLTAGE_VOLTAGE_HIGH                      SUBIDX_6
#define IT2704_SOURCE_VOLTAGE_VOLTAGE_LOW                       SUBIDX_7
#define IT2704_SOURCE_VOLTAGE_VOLTAGE_MODE                      SUBIDX_8
#define IT2704_SOURCE_VOLTAGE_VOLTAGE_RANGE                     SUBIDX_9
#define IT2704_SOURCE_VOLTAGE_VOLTAGE_SLEW_POSITIVE             SUBIDX_10
#define IT2704_SOURCE_VOLTAGE_VOLTAGE_SLEW_NEGATIVE             SUBIDX_11
#define IT2704_SOURCE_VOLTAGE_VOLTAGE_SLEW_TIME_POSITIVE        SUBIDX_12
#define IT2704_SOURCE_VOLTAGE_VOLTAGE_SLEW_TIME_NEGATIVE        SUBIDX_13
#define IT2704_SOURCE_VOLTAGE_VOLTAGE_SLEW_COUPLE               SUBIDX_14
#define IT2704_SOURCE_VOLTAGE_VOLTAGE_SLEW_POSITIVE_MAX         SUBIDX_15
#define IT2704_SOURCE_VOLTAGE_VOLTAGE_SLEW_NEGATIVE_MAX         SUBIDX_16
#define IT2704_SOURCE_VOLTAGE_INTER_RESISTANCE_STATE            SUBIDX_17
#define IT2704_SOURCE_VOLTAGE_INTER_RESISTANCE_LEVEL            SUBIDX_18
#define IT2704_SOURCE_VOLTAGE_BSIM_LEVEL                        SUBIDX_19
#define IT2704_SOURCE_VOLTAGE_INHIBIT_MODE                      SUBIDX_20
#define IT2704_SOURCE_VOLTAGE_INHIBIT_VON                       SUBIDX_21
#define IT2704_SOURCE_VOLTAGE_INHIBIT_VOFF                      SUBIDX_22
#define IT2704_SOURCE_VOLTAGE_OVER_VOLTAGE_PROTECTON_STATE      SUBIDX_23
#define IT2704_SOURCE_VOLTAGE_OVER_VOLTAGE_PROTECTON_POSITIVE   SUBIDX_24
#define IT2704_SOURCE_VOLTAGE_OVER_VOLTAGE_PROTECTON_NEGATIVE   SUBIDX_25
#define IT2704_SOURCE_VOLTAGE_OVER_VOLTAGE_PROTECTON_DELAY      SUBIDX_26
#define IT2704_SOURCE_VOLTAGE_UNDER_VOLTAGE_PROTECTION_STATE    SUBIDX_27
#define IT2704_SOURCE_VOLTAGE_UNDER_VOLTAGE_PROTECTION_POSITIVE SUBIDX_28
#define IT2704_SOURCE_VOLTAGE_UNDER_VOLTAGE_PROTECTION_NEGATIVE SUBIDX_29
#define IT2704_SOURCE_VOLTAGE_UNDER_VOLTAGE_PROTECTION_DELAY    SUBIDX_30
#define IT2704_SOURCE_VOLTAGE_UNDER_VOLTAGE_PROTECTION_WARM     SUBIDX_31

#define IT2704_SOURCE_POWER                                     0x3004U
#define IT2704_SOURCE_POWER_POWER_LEVEL                         SUBIDX_1
#define IT2704_SOURCE_POWER_POWER_TRIGGRED                      SUBIDX_2
#define IT2704_SOURCE_POWER_POWER_LIMIT_POSITIVE                SUBIDX_3
#define IT2704_SOURCE_POWER_POWER_LIMIT_NEGATIVE                SUBIDX_4
#define IT2704_SOURCE_POWER_POWER_LIMIT_COUPLE                  SUBIDX_5
#define IT2704_SOURCE_POWER_POWER_SLEW_POSITIVE                 SUBIDX_6
#define IT2704_SOURCE_POWER_POWER_SLEW_NEGATIVE                 SUBIDX_7
#define IT2704_SOURCE_POWER_POWER_SLEW_COUPLE                   SUBIDX_8
#define IT2704_SOURCE_POWER_POWER_SLEW_POSITIVE_MAX             SUBIDX_9
#define IT2704_SOURCE_POWER_POWER_SLEW_NEGATIVE_MAX             SUBIDX_10
#define IT2704_SOURCE_POWER_OVER_POWER_PROTECT_STATE            SUBIDX_11
#define IT2704_SOURCE_POWER_OVER_POWER_PROTECT_POSITIVE         SUBIDX_12
#define IT2704_SOURCE_POWER_OVER_POWER_PROTECT_NEGATIVE         SUBIDX_13
#define IT2704_SOURCE_POWER_OVER_POWER_PROTECT_DELAY            SUBIDX_14

#define IT2704_SOURCE_RESISTANCE                                0x3005U
#define IT2704_SOURCE_RESISTANCE_RESISTANCE_LEVEL               SUBIDX_1
#define IT2704_SOURCE_RESISTANCE_RESISTANCE_TRIGGRED            SUBIDX_2
#define IT2704_SOURCE_RESISTANCE_RESISTANCE_SLEW_POSITIVE       SUBIDX_3
#define IT2704_SOURCE_RESISTANCE_RESISTANCE_SLEW_NEGATIVE       SUBIDX_4
#define IT2704_SOURCE_RESISTANCE_RESISTANCE_COUPLE              SUBIDX_5
#define IT2704_SOURCE_RESISTANCE_RESISTANCE_SLEW_POSITIVE_MAX   SUBIDX_6
#define IT2704_SOURCE_RESISTANCE_RESISTANCE_SLEW_NEGATIVE_MAX   SUBIDX_7

#define IT2704_SOURCE_FUNCTION                                  0x3006U
#define IT2704_SOURCE_FUNCTION_FUNCTION                         SUBIDX_1

#define IT2704_SOURCE_FILE                                      0x3007U
#define IT2704_SOURCE_FILE_SAVE_BANK                            SUBIDX_1
#define IT2704_SOURCE_FILE_RECALL_BANK                          SUBIDX_2
#define IT2704_SOURCE_FILE_DELETE_BANCK                         SUBIDX_3

#define IT2704_OUTPUT                                           0x3008U
#define IT2704_OUTPUT_ONOFF_STATE                               SUBIDX_1
#define IT2704_OUTPUT_PROTECT_CLEAR                             SUBIDX_2
#define IT2704_OUTPUT_SHORT_MODE                                SUBIDX_3
#define IT2704_OUTPUT_RISE_DELAY                                SUBIDX_4
#define IT2704_OUTPUT_FALL_DELAY                                SUBIDX_5
#define IT2704_OUTPUT_REGULAR_SPEED                             SUBIDX_6
#define IT2704_OUTPUT_RELAY_LOCK_STATE                          SUBIDX_7
#define IT2704_OUTPUT_VOLTAGE_RETURN_ZERO_LEVEL                 SUBIDX_8
#define IT2704_OUTPUT_FOLDBACK_MODE                             SUBIDX_9
#define IT2704_OUTPUT_FOLDBACK_DELAY                            SUBIDX_10

#define IT2704_SENSE                                            0x3009U
#define IT2704_SENSE_SENSE_STATE                                SUBIDX_1
#define IT2704_SENSE_SENSE_CURRENT_RANGE                        SUBIDX_2
#define IT2704_SENSE_SENSE_CURRENT_AUTO_RANGE                   SUBIDX_3
#define IT2704_SENSE_SENSE_VOLTAGE_RANGE                        SUBIDX_4
#define IT2704_SENSE_SENSE_VOLTAGE_AUTO_RANGE                   SUBIDX_5
#define IT2704_SENSE_SENSE_SWEEP_POINTS                         SUBIDX_6
#define IT2704_SENSE_SENSE_SWEEP_OFFSET_POINTS                  SUBIDX_7
#define IT2704_SENSE_SENSE_TIME_INTERVAL                        SUBIDX_8
#define IT2704_SENSE_SENSE_APERTURE                             SUBIDX_9
#define IT2704_SENSE_SENSE_NPLC                                 SUBIDX_10

#define IT2704_STATUS                                           0x030AU
#define IT2704_STATUS_OPERATION_REGISTER                        SUBIDX_1
#define IT2704_STATUS_QUESTIONABLE_REGISTER                     SUBIDX_2

#define IT2704_METER                                            0x300BU
#define IT2704_METER_VOLTAGE                                    SUBIDX_1
#define IT2704_METER_CURRENT                                    SUBIDX_2
#define IT2704_METER_POWER                                      SUBIDX_3
#define IT2704_METER_CURRENT_ACDC                               SUBIDX_4
#define IT2704_METER_VOLTAGE_ACDC                               SUBIDX_5
#define IT2704_METER_CURRENT_MAX                                SUBIDX_6
#define IT2704_METER_CURRENT_MIN                                SUBIDX_7
#define IT2704_METER_VOLTAGE_MAX                                SUBIDX_8
#define IT2704_METER_VOLTAGE_MIN                                SUBIDX_9
#define IT2704_METER_POWER_MAX                                  SUBIDX_10
#define IT2704_METER_POWER_MIN                                  SUBIDX_11
#define IT2704_METER_AHOUR                                      SUBIDX_12
#define IT2704_METER_WHOUR                                      SUBIDX_13
#define IT2704_METER_ON_TIME                                    SUBIDX_14

#endif //CONFIGIT2704_H
