#include "./src/lvgl/lv_port/lv_port_disp.h"

//#include "./src/lvgl/lv_port/lv_port_indev.h"
//#include "./src/touch/gt911_lite.h"
#include "touch.h"

#include "./src/UI/screenbase.h"
#include "./src/UI/screen1.h"
#include "./src/UI/screen2.h"
#include "./src/UI/screen3.h"
#include "./src/UI/ScreenPower.h"
#include "./src/UI/ScreenLogger.h"
#include "./src/UI/ScreenSettings.h"
#include "./src/UI/sevensegment.h"
#include "./src/UI/matrix_screen.h"
#include "./src/UI/screensaver.h"
#include "./src/Fonts/fonts.h"