// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.3.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

#ifdef __cpp_constexpr
#define __pio_const constexpr
#else
#define __pio_const const
#endif

// ----- //
// vsync //
// ----- //

#define vsync_wrap_target 1
#define vsync_wrap 13
#define vsync_pio_version 0

#define vsync_T1 10
#define vsync_T2 8
#define vsync_T3 20

static __pio_const uint16_t vsync_program_instructions[] = {
    0x98a0, //  0: pull   block           side 1
            //     .wrap_target
    0xf82a, //  1: set    x, 10           side 1
    0x38c2, //  2: wait   1 irq, 2        side 1
    0x1842, //  3: jmp    x--, 2          side 1
    0xf028, //  4: set    x, 8            side 0
    0x30c2, //  5: wait   1 irq, 2        side 0
    0x1045, //  6: jmp    x--, 5          side 0
    0xf834, //  7: set    x, 20           side 1
    0x38c2, //  8: wait   1 irq, 2        side 1
    0x1848, //  9: jmp    x--, 8          side 1
    0xb827, // 10: mov    x, osr          side 1
    0xd801, // 11: irq    nowait 1        side 1
    0x38c2, // 12: wait   1 irq, 2        side 1
    0x184c, // 13: jmp    x--, 12         side 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static __pio_const struct pio_program vsync_program = {
    .instructions = vsync_program_instructions,
    .length = 14,
    .origin = -1,
    .pio_version = vsync_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config vsync_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + vsync_wrap_target, offset + vsync_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

// ----- //
// hsync //
// ----- //

#define hsync_wrap_target 2
#define hsync_wrap 15
#define hsync_pio_version 0

#define hsync_T1 10
#define hsync_T2 8

static __pio_const uint16_t hsync_program_instructions[] = {
    0x80a0, //  0: pull   block
    0xa047, //  1: mov    y, osr
            //     .wrap_target
    0xfc2a, //  2: set    x, 10           side 3
    0xb442, //  3: nop                    side 1
    0x1c43, //  4: jmp    x--, 3          side 3
    0xd402, //  5: irq    nowait 2        side 1
    0xf828, //  6: set    x, 8            side 2
    0xb042, //  7: nop                    side 0
    0x1847, //  8: jmp    x--, 7          side 2
    0xf438, //  9: set    x, 24           side 1
    0xbd42, // 10: nop                    side 3 [1]
    0x144a, // 11: jmp    x--, 10         side 1
    0xbc22, // 12: mov    x, y            side 3
    0xb442, // 13: nop                    side 1
    0xb442, // 14: nop                    side 1
    0x1c4d, // 15: jmp    x--, 13         side 3
            //     .wrap
};

#if !PICO_NO_HARDWARE
static __pio_const struct pio_program hsync_program = {
    .instructions = hsync_program_instructions,
    .length = 16,
    .origin = -1,
    .pio_version = hsync_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config hsync_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + hsync_wrap_target, offset + hsync_wrap);
    sm_config_set_sideset(&c, 3, true, false);
    return c;
}
#endif

// --- //
// rgb //
// --- //

#define rgb_wrap_target 2
#define rgb_wrap 12
#define rgb_pio_version 0

static __pio_const uint16_t rgb_program_instructions[] = {
    0x80a0, //  0: pull   block
    0xa047, //  1: mov    y, osr
            //     .wrap_target
    0xb022, //  2: mov    x, y                   [16]
    0x20a4, //  3: wait   1 pin, 4
    0x80a0, //  4: pull   block
    0x6010, //  5: out    pins, 16
    0xa042, //  6: nop
    0xa042, //  7: nop
    0xa042, //  8: nop
    0x2027, //  9: wait   0 pin, 7
    0x20a7, // 10: wait   1 pin, 7
    0x0044, // 11: jmp    x--, 4
    0xc000, // 12: irq    nowait 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static __pio_const struct pio_program rgb_program = {
    .instructions = rgb_program_instructions,
    .length = 13,
    .origin = -1,
    .pio_version = rgb_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config rgb_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + rgb_wrap_target, offset + rgb_wrap);
    return c;
}
#endif

// ------ //
// rgb_de //
// ------ //

#define rgb_de_wrap_target 1
#define rgb_de_wrap 16
#define rgb_de_pio_version 0

#define rgb_de_T1 20

static __pio_const uint16_t rgb_de_program_instructions[] = {
    0x90a0, //  0: pull   block           side 0
            //     .wrap_target
    0xb047, //  1: mov    y, osr          side 0
    0xf034, //  2: set    x, 20           side 0
    0x3025, //  3: wait   0 pin, 5        side 0
    0x30a5, //  4: wait   1 pin, 5        side 0
    0x3026, //  5: wait   0 pin, 6        side 0
    0x30a6, //  6: wait   1 pin, 6        side 0
    0x1045, //  7: jmp    x--, 5          side 0
    0x3026, //  8: wait   0 pin, 6        side 0
    0x30a6, //  9: wait   1 pin, 6        side 0
    0xf038, // 10: set    x, 24           side 0
    0x3027, // 11: wait   0 pin, 7        side 0
    0x31a7, // 12: wait   1 pin, 7        side 0 [1]
    0x104b, // 13: jmp    x--, 11         side 0
    0x30a7, // 14: wait   1 pin, 7        side 0
    0x38c0, // 15: wait   1 irq, 0        side 1
    0x1088, // 16: jmp    y--, 8          side 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static __pio_const struct pio_program rgb_de_program = {
    .instructions = rgb_de_program_instructions,
    .length = 17,
    .origin = -1,
    .pio_version = rgb_de_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config rgb_de_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + rgb_de_wrap_target, offset + rgb_de_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}

#include "hardware/clocks.h"
#include "hardware/pio.h"
static inline void pio_rgb_panel_init(PIO pio, uint sm, uint offset, 
                                     uint de_pin, uint vsync_pin, uint hsync_pin, uint pclk_pin,
                                     uint r0_pin, uint32_t prefer_speed) {
    pio_gpio_init(pio, de_pin);
    pio_gpio_init(pio, vsync_pin);
    pio_gpio_init(pio, hsync_pin);
    pio_gpio_init(pio, pclk_pin);
    pio_sm_set_consecutive_pindirs(pio, sm, de_pin, 1, true);
    pio_sm_set_consecutive_pindirs(pio, sm, vsync_pin, 1, true);
    pio_sm_set_consecutive_pindirs(pio, sm, hsync_pin, 1, true);
    pio_sm_set_consecutive_pindirs(pio, sm, pclk_pin, 1, true);
    for (int i = 0; i < 16; i++) {
        pio_gpio_init(pio, r0_pin + i);
        pio_sm_set_consecutive_pindirs(pio, sm, r0_pin + i, 1, true);
    }
    pio_sm_config c = pio_get_default_sm_config();
    float div = (float)clock_get_hz(clk_sys) / prefer_speed;
    sm_config_set_clkdiv(&c, div);
    pio_sm_init(pio, sm, offset, &c);
}

#endif
